module:
  imports:
  - path: github.com/hugomods/images

baseURL: https://testamentenjoyment.net
title: TESTAMENT✙ENJOYMENT
languageCode: en-US
theme: [PaperMod]

buildDrafts: false
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Play SpikeOut
          url: spikeout
          weight: 1
        - name: Articles
          url: articles
          weight: 2
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: About
          url: about
          weight: 15
        - name: RSS
          url: /index.xml
          weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: TESTAMENT TESTAMENT TESTAMENT
  author: Durandal
  blueSkyAuthor: did:plc:b7wncmt7q7rqwzu5enl5gsya

  defaultTheme: auto
  ShowDrafts: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  TocOpen: true
  comments: true

  mainsections:
    - articles
    - spikeout

  footer:
    text: The text content of this site is [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

  homeInfoParams:
    Content: >
      - ![Homepage cover image](img/front-cover.webp)

      - 

      - Welcome to my blog! I'm **Durandal / TestamentEnjoyment**. 
      
      - Amongst other things I like talking about game design, action games and arcade-style games in particular. You can find an assorted list of my writings **[here](/articles)**.

      - I have also written a lot about SpikeOut. If you want to learn how to play SpikeOut, click **[this link](/spikeout/install-spikeout)**.

      - 

      - You can contact me through my socials or my e-mail below:

  socialIcons:
    - name: github
      title: GitHub projects
      url: "https://github.com/GriekseEi"
    - name: bluesky
      title: TestamentEnjoyment on BlueSky
      url: https://bsky.app/profile/did:plc:b7wncmt7q7rqwzu5enl5gsya
    - name: youtube
      title: TestamentEnjoyment on YouTube
      url: https://www.youtube.com/@TestamentEnjoymentGaming-rv2jw
    - name: email
      title: testamentenjoyment@gmail.com
      url: mailto:testamentenjoyment@gmail.com
    - name: RSS
      title: TestamentEnjoyment RSS feed
      url: /index.xml

  webButtons:
    - alt: Status Cafe
      src: https://status.cafe/assets/button.png
      link: https://status.cafe
    - alt: I was on Cohost!
      src: iwasoncohost.gif
    - alt: I use Arch, btw
      src: archlinux.gif
    - alt: SEGA ONLINE
      src: sega_online.gif

  assets:
    disableHLJS: true